GET http://localhost:9001/file/delete?file_id=9094ce1c-e402-4e07-a363-a3383a471010
Accept: application/json


###
GET http://localhost:9001/file/getInfo?file_id=9094ce1c-e402-4e07-a363-a3383a471010
Accept: application/json

###
GET http://localhost:9001/file/download?file_id=9094ce1c-e402-4e07-a363-a3383a471010
Accept: application/json

### xx
POST http://localhost:9001/file/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="file.txt"

< ./relative/path/to/local_file.txt
--WebAppBoundary--